### PR TITLE
Add `:exsyslog` to included_applications in readme

### LINKED ISSUE #2: badmatch
I get this trying to start my app on my server. It works locally on a mac. config is below, any ideas?

```
=INFO REPORT==== 9-Nov-2015::11:11:51 ===
    application: logger
    exited: {{shutdown,
              {failed_to_start_child,'Elixir.Logger.Watcher',
               {'EXIT',
                {{badmatch,
                  {error,
                   {undef,
                    [{'Elixir.ExSyslog',init,
                      [{'Elixir.ExSyslog',exsyslog}],
                      []},
                     {'Elixir.GenEvent',do_handler,3,
                      [{file,"lib/gen_event.ex"},{line,1093}]},
                     {'Elixir.GenEvent',do_add_handler,5,
                      [{file,"lib/gen_event.ex"},{line,1050}]},
                     {'Elixir.GenEvent',handle_msg,5,
                      [{file,"lib/gen_event.ex"},{line,711}]},
                     {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,240}]}]}}},
                 [{'Elixir.Logger.Watcher','-start_link/3-fun-0-',2,
                   [{file,"lib/logger/watcher.ex"},{line,19}]},
                  {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
                   [{file,"lib/enum.ex"},{line,1387}]},
                  {'Elixir.Logger.Watcher',start_link,3,
                   [{file,"lib/logger/watcher.ex"},{line,18}]},
                  {supervisor,do_start_child,2,
                   [{file,"supervisor.erl"},{line,343}]},
                  {supervisor,start_children,3,
                   [{file,"supervisor.erl"},{line,326}]},
                  {supervisor,init_children,2,
                   [{file,"supervisor.erl"},{line,292}]},
                  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
                  {proc_lib,init_p_do_apply,3,
                   [{file,"proc_lib.erl"},{line,240}]}]}}}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: permanent
```

``` elixir
config :logger,
  backends: [
    {ExSyslog, :exsyslog},
  ]

config :logger, :exsyslog,
  format: "$date $time [$level] $levelpad$node $metadata $message",
  metadata: [:module, :line, :function],
  ident: "Booking",
  facility: :local0,
  option: [:pid, :cons]
```

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #2

### CODE REVIEW

**Comment by aaronjensen** [comment]
Ugh, this actually breaks dev. Something is wrong here. Have you used this package successfully in production?

**Comment by aaronjensen** [comment]
Nevermind, that was a red herring. I had a build for another platform in the way. This pull should be good.

**Comment by aaronjensen** [comment]
This seems to be good to go now.

**Comment by mr-bt** [comment]
I've work around it by including in releases :exsyslog in applications. But your solution is much more elegant. I'll merge and publish to hex today. Thank you :heart:

**Pull request merged**
